### ISSUE TITLE
Add support for using npmAuthIdent instead of npmToken

### ISSUE THREAD

**Issue by kobelobster** [dmeents/semantic-release-yarn#3]
Hello,

in our company we are using Microsoft Azure DevOps and just upgraded to yarn v3. Since you wrote this library you know why we need it! Thanks for it.

Sadly, Microsoft Azure DevOps doesn't allow creation of npmToken. We just don't have that value. In Microsoft, we can just create npmAuthIdent.

It would be really good if we could add functionality to allow also authentication with npmAuthToken

For this I have created a PR that I will link!

**Comment by dmeents** [comment]
Great PR, thanks for the contribution!
