### ISSUE TITLE
"Packages will be published to the registry specified in the package.json file"

### ISSUE THREAD

**Issue by martinstark** [dmeents/semantic-release-yarn#7]
I've just migrated from `semantic-release-npm`, it would be nice if the package was able to resolve registry from `npmScopes` declared in the `.yarnrc.yml` file. Reading registry from the `publishConfig.registry` field to the `package.json` creates redundant configuration.

With `npmScopes` set up in either `.yarnrc.yml` or in ci workflow files, does the `semantic-release-yarn` plugin even need to resolve and overwrite the registry?

**Comment by dmeents** [comment]
Sorry for the late reply, I'm looking into this now, because you make some good points! Thanks for the feedback!

**Comment by dmeents** [comment]
Got this working I think, let me know if you run into any issues: https://github.com/dmeents/semantic-release-yarn/commit/80cad06ea60ea648ad36bb5293f10aa9b2d6ac0e
